services:
  db:
    image: postgres:15
    container_name: algodatta-db
    environment:
      POSTGRES_USER: algouser
      POSTGRES_PASSWORD: algopass
      POSTGRES_DB: algodatta
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/algodatta/pgdata:/var/lib/postgresql/data

  backend:
    healthcheck:
      test: [ "CMD-SHELL", "python -c 'import urllib.request,sys; sys.exit(0) if urllib.request.urlopen(\"http://127.0.0.1:8000/api/healthz\").status==200 else sys.exit(1)'" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: algodatta-backend
    environment:
      DATABASE_URL: postgresql+psycopg://algouser:algopass@db:5432/algodatta
      JWT_SECRET: super-secret-change-me
      # CORS must allow your web app origin(s) and send credentials
      CORS_ORIGINS: https://www.algodatta.com,https://algodatta.com,http://localhost:3000

      # --- Required for Cognito Managed Login (Option A) ---
      OIDC_ISSUER: "https://cognito-idp.<REGION>.amazonaws.com/<USER_POOL_ID>"
      OIDC_CLIENT_ID: "<your-app-client-id>"

      # --- Optional: first-login role assignment (used by users_service.py) ---
      DEFAULT_ROLE: "trader"
      # Keep JSON single-quoted in YAML to avoid parsing issues
      ROLE_EMAIL_MAP: '{"admin":["admin@yourdomain.com"],"analyst":["analyst@yourdomain.com"],"trader":["trader@yourdomain.com"]}'
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: algodatta-frontend
    environment:
      # Local dev points to backend port binding
      NEXT_PUBLIC_API_BASE: "http://localhost:8000"

      # --- Required by the Next.js OIDC bridge (Option A) ---
      # For PRODUCTION (on Lightsail/Nginx), set these to your real values:
      # OIDC_CLIENT_ID: "<your-app-client-id>"
      # OIDC_REDIRECT_URI: "https://www.algodatta.com/auth/callback"
      # COGNITO_DOMAIN: "https://login.algodatta.com"
      # SESSION_COOKIE_DOMAIN: ".algodatta.com"
      #
      # For LOCAL DEV leave SESSION_COOKIE_DOMAIN unset (cookies behave better on localhost).
      # Example dev values if testing Cognito locally:
      # OIDC_CLIENT_ID: "<dev-app-client-id>"
      # OIDC_REDIRECT_URI: "http://localhost:3000/auth/callback"
      # COGNITO_DOMAIN: "https://<your-cognito-domain>.auth.<REGION>.amazoncognito.com"
    depends_on:
      - backend
    ports:
      - "3000:3000"
