services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: algodatta-frontend
    ports:
    - "127.0.0.1:3000:3000"
    restart: always
    depends_on:
    - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: algodatta-backend
    ports:
    - "127.0.0.1:8000:8000"
    restart: always
    depends_on:
    - postgres
    environment:
      EXEC_PUBLISHER_POLL_ENABLED: '1'
      EXEC_PUBLISHER_POLL_INTERVAL: '5'
      EXEC_PUBLISHER_LOOKBACK_SECONDS: '120'
  postgres:
    image: postgres:15
    container_name: algodatta-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: algodatta
    ports:
    - 5432:5432
    volumes:
    - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata: null
