
services:
  db:
    image: postgres:15
    container_name: algodatta-db
    environment:
      POSTGRES_USER: algouser
      POSTGRES_PASSWORD: algopass
      POSTGRES_DB: algodatta
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: algodatta-backend
    environment:
      DATABASE_URL: postgresql+psycopg://algouser:algopass@db:5432/algodatta
      JWT_SECRET: super-secret-change-me
      CORS_ORIGINS: https://www.algodatta.com,https://algodatta.com,http://localhost:3000
    depends_on:
      - db
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: algodatta-frontend
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:8000
    depends_on:
      - backend
    ports:
      - "3000:3000"
volumes:
  pgdata:
